### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yin0110**
finish API2

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online testing URLs.

**Comment by yin0110** [comment]
Hello 我是莊尹淳，已經完成作業
http://54.159.5.246:3000/api/attraction?page=1
http://54.159.5.246:3000/api/attraction?page=0&keyword=館
http://54.159.5.246:3000/api/attraction/7

**Comment by yin0110** [comment]
Hello 我是莊尹淳（yin），已經完成作業
http://54.159.5.246:3000/api/attraction?page=1
http://54.159.5.246:3000/api/attraction?page=0&keyword=館
http://54.159.5.246:3000/api/attraction/7

**Comment by yin0110** [comment]
Hello 我是莊尹淳（yin），已經完成作業
http://54.159.5.246:3000/api/attraction?page=1
http://54.159.5.246:3000/api/attraction?page=0&keyword=館
http://54.159.5.246:3000/api/attraction/7

**Pull request merged**
